##第一次运行时使用，下载zabbix repo
- name: get zabbix repo
  shell: /usr/bin/rpm -Uvh https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm

##安装zabbix，第一次及更新时使用
- name: install zabbix-agent
  yum: name=zabbix-agent state=latest

##如果zabbix客户端已安装完毕，可以注释掉上面两个
- name: copy zabbix-agent conf
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  tags:
  - conf
  notify:
  - restart zabbix-agent
- name: start zabbix-agent
  service: name=zabbix-agent  state=started enabled=true
